myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from kublog import views


admin.site.site_header = 'kublog管理者用サイト'
admin.site.index_title = 'ホーム'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home , name='home'),
    path('append_post/', views.append_post, name='append_post'),
    path('post_one/<int:post_id>/', views.post_one, name='post_one'),
    path('post_one/post_delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('post_one/post_edit/<int:post_id>/', views.post_edit, name='post_edit'),
    path('contact_form/', views.contact_form, name='contact_form'),
    path('search_classroom/', views.search_classroom, name='search_classroom'),
    path('accounts/', include('allauth.urls')),
    
]

accounts/models.py
from django.contrib.auth.models import UserManager, AbstractUser
 
class CustomUserManager(UserManager):
    use_in_migrations = True
 
    def _create_user(self, email, username, password, **extra_fields):
        # create_user と create_superuser の共通処理
        if not email:
            raise ValueError('email must be set')
        if not username:
            raise ValueError('username must be set')
 
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
 
        return user
 
    def create_user(self, username, email=None, password=None, **extra_fields):
 
        if not email:
            raise ValueError('email must be set')
        if not username:
            raise ValueError('username must be set')
 
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
 
        return self._create_user(email, username, password, **extra_fields)
 
    def create_superuser(self, username, email=None, password=None, **extra_fields):
 
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
 
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
 
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
 
        return self._create_user(email, username, password, **extra_fields)
    

class CustomUser(AbstractUser):
    objects = CustomUserManager()

    def __str__(self):
        return self.email

kublog/models.py
from django.db import models
from kublog import consts

class PostOne(models.Model):
    title = models.CharField(max_length=30)
    date = models.DateField(auto_now=True)
    content = models.CharField(max_length=2200)
    place = models.CharField(choices=consts.PREFECTURES,max_length=30)
    created_by = models.CharField(max_length=30)

class Contact(models.Model):
    contact_name = models.CharField(max_length=50)
    contact_email = models.EmailField()
    contact_message = models.CharField(max_length=2200)

kublog/forms.py
from django import forms
from kublog.models import Contact, PostOne

class PostOneForm(forms.ModelForm):
    class Meta:
        model = PostOne
        fields = ('title','content','place')
        widgets = {
            'content': forms.Textarea(attrs={'rows':10, 'cols':20}),
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('contact_name','contact_message','contact_email')
        widgets = {
            'contact_message': forms.Textarea(attrs={'rows':10, 'cols':20}),
        }
    
class PostSearchForm(forms.Form):
    keywords = forms.CharField(max_length=50,)
        

kublog/templates/append_post.html
{% extends 'base.html'%}
{% load widget_tweaks %}
{% block head_title %}新規投稿{% endblock %}
{% block content %}
<div class="form">
    <h2>新規投稿追加</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form_set">
            <label for="id_title">タイトル</label>
            {% if form.title.errors %}
            {% render_field form.title class="form_information_input_invalid" id="id_title" %}
            {% for error in form.title.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.title class="form_information_input" id="id_title" %}
            {% endif %}
        </div>
        <div class="form_set">
            <label for="id_place">場所</label>
            <select name="place" required="" id="id_place" class="form_information_input">
                <option value="" selected="">---</option>
              
                <option value="食堂">食堂</option>
              
                <option value="500号館">500号館</option>
              
                <option value="600号館">600号館</option>
              
                <option value="700号館">700号館</option>
              
                <option value="800号館">800号館</option>
              
                <option value="900号館">900号館</option>
              
                <option value="1000号館">1000号館</option>
              
                <option value="御井本館">御井本館</option>
              
                <option value="御井図書館">御井図書館</option>
              
                <option value="第1学生部室棟">第1学生部室棟</option>
              
                <option value="第2学生部室棟">第2学生部室棟</option>
              
                <option value="御井学館">御井学館</option>
              
                <option value="御井学生会館">御井学生会館</option>
              
                <option value="千歳会館">千歳会館</option>
              
                <option value="第2体育館">第2体育館</option>
              
                <option value="第3学生部室棟">第3学生部室棟</option>
              
                <option value="テニスコート">テニスコート</option>
              
                <option value="インターナショナル・ハウス">インターナショナル・ハウス</option>
              
                <option value="みいアリーナ">みいアリーナ</option>
              
                <option value="学生寮">学生寮</option>
              
                <option value="駐輪場">駐輪場</option>
              
                <option value="グラウンド">グラウンド</option>
              
                <option value="弓道場">弓道場</option>
              
                <option value="茶室">茶室</option>
              
                <option value="器楽室">器楽室</option>
              
              </select>
        </div>
        <div class="form_set">
            <label for="id_content">内容</label>
            {% if form.content.errors %}
            {% render_field form.content class="form_information_input_invalid" id="id_content" %}
            {% for error in form.content.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.content class="form_information_input" id="id_content" %}
            {% endif %}
        </div>
        <input type="hidden" name="created_by" maxlength="30" value="{{request.user}}">
        {{ form.non_field_errors }}
        <div class="normal_button">
            <button type="submit">追加</button>
        </div>
    </form>
    </div>
{% endblock %}

kublog/templates/base.html
{% load rules %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">
    <title>{% block head_title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'kublog/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid container">
        <div class="navbar-brand"><a href="{% url 'home' %}">KU-INFO</a></div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
            </li>
            {% has_perm 'is_editor' user as is_editor %}
            {% if is_editor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'append_post'%}">新規追加</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'search_classroom'%}">教室使用状況</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact_form'%}">Contact</a>
            </li>
            <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'account_logout'%}">Logout</a>
              {% else %}
              <a class="nav-link" href="{% url 'account_login'%}">Login</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="../static/kublog/js/script.js"></script>
    <footer>
      <div class="footer_flex">
      <div class="kublog_icon">
        <a href="{% url 'home' %}">KU-INFO</a>
      </div>
      <div class="icon8">
        <div class="icon8_one">
          <a target="_blank" href="https://icons8.com/icon/118557/github">GitHub</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </div>
        <div class="icon8_one">
          <a target="_blank" href="https://icons8.com/icon/17949/googleのロゴ">Google</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </div>
      </div>
      </div>
    </footer>
</body>
</html>

kublog/templates/contact_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block head_title %}お問い合わせ{% endblock %}
{% block content %}
<div class="form">
    <h2>Contact</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form_set">
            <label for="id_contact_name">お名前</label>
            {% if form.contact_name.errors %}
            {% render_field form.contact_name class="form_information_input_invalid" id="id_contact_name" %}
            {% for error in form.contact_name.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.contact_name class="form_information_input" id="id_contact_name" %}
            {% endif %}
        </div>
        <div class="form_set">
            <label for="id_contact_email">メールアドレス</label>
            {% if form.contact_email.errors %}
            {% render_field form.contact_email class="form_information_input_invalid" id="id_contact_email" %}
            {% for error in form.contact_email.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.contact_email class="form_information_input" id="id_contact_email" %}
            {% endif %}
        </div>
        <div class="form_set">
            <label for="id_contact_message">問い合わせ内容</label>
            {% if form.contact_message.errors %}
            {% render_field form.contact_message class="form_information_input_invalid" id="id_contact_message" %}
            {% for error in form.contact_message.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.contact_message class="form_information_input" id="id_contact_message" %}
            {% endif %}
        </div>
        {{ form.non_field_errors }}
        <div class="normal_button">
            <button type="submit" onclick="return confirm('送信してよろしいですか')">送信</button>
        </div>
    </form>
</div>
{% endblock %}

kublog/templates/index.html
{% extends 'base.html'%}
{% load widget_tweaks %}
{% load rules %}
{% block head_title %}Home{% endblock %}
{% block content %}
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark main">
  <div class="col-md-6 px-0 main_text">
    <h1 class="display-4 fst-italic">Welcome to KU-INFO</h1>
    <p class="lead my-3">Kurume University's information site</p>
  </div>
</div>
<div class="container">
  <div class="contents">
    <div class="content_1">
      <div class="new_list">
        <div class="list_title_2">
          <h2>新規投稿</h2>
        </div>
        {% if post_list %}
          {%for post in post_list %}
          <div class="new_list_card">
            <div class="card_header">
              <div class="card_header_title">
                <h3>{{post.title}}</h3>
              </div>
            </div>
            <div class="card_header_mini">
              <div class="mini_title">{{post.date}}</div>
              <div class="mini_title">{{post.place}}</div>
            </div>
            <div class="card_content">
              <p>{{post.content | truncatechars:80}}</p>
            </div>
            <div class="card_more_button">
              <a href="{%url 'post_one' post.id%}">read more >></a>
            </div>
          </div>
          {%endfor%}
          <div class="paginator">
            {% if post_list.has_previous %}
            <a href="?page={{ post_list.previous_page_number }}">&lt; 前のページ</a>
            {% endif %}
        
            {{ post_list.number }}ページ
        
            {% if post_list.has_next %}
              <a href="?page={{ post_list.next_page_number }}">次のページ &gt;</a>
            {% endif %}
          </div>
        {% else %}
        <div class="no_post_list_home">
          <p>まだ投稿がありません。</p>
          {% has_perm 'is_editor' user as is_editor%}
          {% if is_editor %}
          <a href="{% url 'append_post'%}">新規作成</a>
          {% endif %}
        </div>
        {% endif %}
      
      </div>
      <div class="place_map">
        <div class="list_title_2">
          <h2>地図</h2>
        </div>
        <div class="iframe">
          <div class="iframe-wrap"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d495.66323345355863!2d130.54592594920493!3d33.30805619845235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3541a425039d2aa5%3A0xf319749f2e553a09!2z5LmF55WZ57Gz5aSn5a2m5b6h5LqV44Kt44Oj44Oz44OR44K5!5e0!3m2!1sja!2sjp!4v1661215348470!5m2!1sja!2sjp" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
        </div>
      </div>
    </div>
    <div class="content_2">
      <div class="user_status">
        <h4>ユーザー情報</h4>
        <div class="user_name">{{user.username}}</div>
        {% has_perm 'can_edit_user' user as can_edit_user %}
        {% if user.is_staff %}
        <div class="user_type">サイト運営者</div>
        {% elif can_edit_user %}
        <div class="user_type">編集者</div>
        {% else %}
        <div class="user_type">一般ユーザー</div>
        {% endif %}
      </div>
      <div class="author_comment">
        <h4>筆者コメ</h4>
        <p>このサイトを作成したo.k.bです。ぜひ改善してほしい所などがあれば、コンタクトフォームからお願い致します。</p>
      </div>
      <div class="search_form">
        <h4>記事検索フォーム</h4>
        <form id="search" method="get" action="">
          {% render_field form.keywords id="search_box" placeholder="キーワードを入力" %}
          <button type="submit" id="submit_search">検索</button>
          {% if miss %}
          <p>フォーム内容を確認してください</p>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

kublog/templates/no_search_post.html
{% extends 'base.html'%}
{% load rules %}
{% block head_title %}投稿検索結果{% endblock %}
{% block content %}
<div class="no_post_list">
    <h1>投稿が見つかりませんでした</h1>
    {% has_perm 'is_editor' user as is_editor%}
    {% if is_editor %}
    <a href="{% url 'append_post'%}">新規作成する</a>
    {% endif %}
    <a href="{% url 'home'%}">ホームに戻る</a>
</div>
{% endblock %}

kublog/templates/post_edit.html
{% extends 'base.html'%}
{% load widget_tweaks %}
{% block head_title %}投稿編集{% endblock %}
{% block content %}
<div class="form">
    <h2>投稿編集</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form_set">
            <label for="id_title">タイトル</label>
            {% if form.title.errors %}
            {% render_field form.title class="form_information_input_invalid" id="id_title" %}
            {% for error in form.title.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.title class="form_information_input" id="id_title" value="{{post.title}}"%}
            {% endif %}
        </div>
        <div class="form_set">
            <label for="id_place">場所</label>
            <select name="place" required="" id="id_place" class="form_information_input">
                <option value="{{post.place}}">{{post.place}}</option>
              
                <option value="食堂">食堂</option>
              
                <option value="500号館">500号館</option>
              
                <option value="600号館">600号館</option>
              
                <option value="700号館">700号館</option>
              
                <option value="800号館">800号館</option>
              
                <option value="900号館">900号館</option>
              
                <option value="1000号館">1000号館</option>
              
                <option value="御井本館">御井本館</option>
              
                <option value="御井図書館">御井図書館</option>
              
                <option value="第1学生部室棟">第1学生部室棟</option>
              
                <option value="第2学生部室棟">第2学生部室棟</option>
              
                <option value="御井学館">御井学館</option>
              
                <option value="御井学生会館">御井学生会館</option>
              
                <option value="千歳会館">千歳会館</option>
              
                <option value="第2体育館">第2体育館</option>
              
                <option value="第3学生部室棟">第3学生部室棟</option>
              
                <option value="テニスコート">テニスコート</option>
              
                <option value="インターナショナル・ハウス">インターナショナル・ハウス</option>
              
                <option value="みいアリーナ">みいアリーナ</option>
              
                <option value="学生寮">学生寮</option>
              
                <option value="駐輪場">駐輪場</option>
              
                <option value="グラウンド">グラウンド</option>
              
                <option value="弓道場">弓道場</option>
              
                <option value="茶室">茶室</option>
              
                <option value="器楽室">器楽室</option>
              
              </select>
        </div>
        <div class="form_set">
            <label for="id_content">内容</label>
            {% if form.content.errors %}
            {% render_field form.content class="form_information_input_invalid" id="id_content" %}
            {% for error in form.content.errors %}
            <div class="error-message">
                {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field form.content class="form_information_input" id="id_content" %}
            {% endif %}
        </div>
        {{ form.non_field_errors }}
        <div class="normal_button">
            <button type="submit" onclick="return confirm('変更してよろしいですか')">変更する</button>
        </div>
    </form>
    </div>
{% endblock %}

kublog/templates/post_list.html
{% extends 'base.html'%}
{% block head_title %}投稿一覧{% endblock %}
{% block content %}
<div class="container">
    <div class="search_post_list">
        <div class="list_title">
            <h2>{{keywords}}の投稿一覧</h2>
        </div>
        {%for post in post_list %}
        <div class="new_list_card">
          <div class="card_header">
            <div class="card_header_title">
              <h3>{{post.title}}</h3>
            </div>
          </div>
          <div class="card_header_mini">
            <div class="mini_title">{{post.date}}</div>
            <div class="mini_title">{{post.place}}</div>
          </div>
          <div class="card_content">
            <p>{{post.content | truncatechars:80}}</p>
          </div>
          <div class="card_more_button">
            <a href="{%url 'post_one' post.id%}">read more >></a>
          </div>
        </div>
        {%endfor%}
        <div class="paginator">
          {% if post_list.has_previous %}
          <a href="?page={{ post_list.previous_page_number }}">&lt; 前のページ</a>
          {% else %}
          <span>&lt; 前のページ</span>
          {% endif %}
      
          {{ post_list.number }}ページ
      
          {% if post_list.has_next %}
          <a href="?page={{ post_list.next_page_number }}">次のページ &gt;</a>
          {% else %}
          <span>次のページ &gt;</span>
          {% endif %}
        </div>
      </div>
    
</div>    
{% endblock %}

kublog/templates/post_one.html
{% extends 'base.html'%}
{% load rules %}
{% block head_title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="post_one">
    <div class="post_one_bg container">
        <div class="post_one_container">
            <div class="post_one_date">
                {{ post.date }}
            </div>
            <div class="post_one_title">
                <h1>{{ post.title }}</h1>
            </div>
            <div class="post_one_place">
                <a href="" class="place_link">{{ post.place }}</a>
            </div>
            <div class="post_one_content">
                {{ post.content }}
            </div>
            {% has_perm 'is_object_editor' user post as is_object_editor %}
            {% if is_object_editor %}
            <div class="post_one_buttons">
                <a href="{% url 'post_delete' post.id%}" onclick="return confirm('本当に削除しますか');">削除</a>
                <a href="{% url 'post_edit' post.id%}">編集</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="post_one_green"></div>
{% endblock %}

kublog/templates/search_post.html
{%extends 'base.html'%}
{% block head_title %}投稿検索結果{% endblock %}
{%block content%}
<div class="search_post_list">
    <div class="list_title_2">
      <h2>'{{keywords}}'の検索結果</h2>
    </div>
    {% if posts %}
      {%for post in posts %}
      <div class="new_list_card">
        <div class="card_header">
          <div class="card_header_title">
            <h3>{{post.title}}</h3>
          </div>
        </div>
        <div class="card_header_mini">
          <div class="mini_title">{{post.date}}</div>
          <div class="mini_title">{{post.place}}</div>
        </div>
        <div class="card_content">
          <p>{{post.content}}</p>
        </div>
        <div class="card_more_button">
          <a href="{%url 'post_one' post.id%}">read more >></a>
        </div>
      </div>
      {%endfor%}
      <div class="paginator">
        {% if posts.has_previous %}
        <a href="?page={{ post_list.previous_page_number }}">&lt; 前のページ</a>
        {% endif %}
    
        {{ posts.number }}ページ
    
        {% if posts.has_next %}
          <a href="?page={{ post_list.next_page_number }}">次のページ &gt;</a>
        {% endif %}
      </div>
    {% else %}
    <div class="no_post_list_home">
      <p>'{{keywords}}'に関する投稿はありません。</p>
    </div>
    {% endif %}
</div>
       
{%endblock%}